force-app/main/default/objects/Quote/fields/Customer_Address__c.field-meta.xml
<CustomField>
    <fullName>Customer_Address__c</fullName>
    <label>Customer Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone__c</fullName>
    <label>Customer Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ATEQ_Quote_Template_Ctrl.cls
//ATEQ_Quote_Template_Ctrl 
public class ATEQ_Quote_Template_Ctrl {
	
    public Quote quote{get;set;}
    public ATEQ_Quote_Template_Ctrl(ApexPages.StandardController stdController) {
        String quoteId = ApexPages.currentPage().getParameters().get('id');
        quote = [SELECT Id, QuoteNumber, CreatedDate, Owner.Name, Owner.Email, Owner.Phone, Customer_Name__c, Customer_Address__c, Customer_Email__c,Customer_Phone__c, GrandTotal,
                    (SELECT Id, Product2.Name, Product2.Description, Product2.SKU__c, Quantity, UnitPrice, TotalPrice FROM QuoteLineItems) FROM Quote WHERE Id=:quoteId];
    }
    
}